name: PWA App Deployment
on:
  push:
    branches:
      - main
jobs:
  version-app:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.next_version.outputs.version }}
    steps:
      - id: match_version
        uses: zwaldowski/match-label-action@v4
        with:
          allowed: major, minor, patch
          default_match: patch
      - id: next_version
        uses: zwaldowski/semver-release-action@v3
        with:
          bump: ${{ steps.run_tests.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: [version-app]
    steps:
      - uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
        env:
          REACT_APP_VERSION_ID: ${{ needs.version-app.outputs.next_version }}
      - name: archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_rc_${{ needs.version-app.outputs.next_version }}
          path: build